'use client';

import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { Activity as ActivityIcon, ArrowUpRight, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, Download, FlaskConical, Layers3, LayoutDashboard, ListFilter, RotateCcw, Search, ShieldCheck, Sparkles, TriangleAlert, TrendingUp, X } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger, useSidebar } from '@/components/ui/sidebar';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Slider } from '@/components/ui/slider';
import { Progress } from '@/components/ui/progress';
import { Pagination, PaginationContent, PaginationItem, PaginationPrevious, PaginationNext } from '@/components/ui/pagination';
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { isBreak, money, notional, seedTrades, simulate, summarize, transitionTrade, type Activity, type Trade } from '@/lib/operations';

type View = 'overview' | 'trades' | 'exceptions' | 'simulator';
const nav = [ { id: 'overview', title: 'Overview', icon: LayoutDashboard }, { id: 'trades', title: 'Trade blotter', icon: Layers3 }, { id: 'exceptions', title: 'Exceptions', icon: ShieldCheck }, { id: 'simulator', title: 'Stress simulator', icon: FlaskConical } ] as const;
const initialActivity: Activity[] = [ { id: 'init-1', text: 'Five settlement exceptions require review', time: '12:40', type: 'exception' }, { id: 'init-2', text: '55 trades settled in the sample batch', time: '12:32', type: 'settlement' }, { id: 'init-3', text: 'Three trades matched and ready for settlement', time: '12:28', type: 'match' } ];
const flow = ['Pending', 'Matched', 'Settled'];

function Badge({ status }: { status: string }) { return <span className={`status status-${status.toLowerCase()}`}>{status === 'Settled' && <Check size={12}/>} {status}</span>; }
function AppNav({ view, setView, count }: { view: View; setView: (v: View) => void; count: number }) {
  const { setOpenMobile } = useSidebar();
  return <Sidebar className="app-sidebar" collapsible="offcanvas">
    <SidebarHeader className="brand-header"><a href="#" className="brand" onClick={e => {e.preventDefault();setView('overview');}}><span className="brand-mark"><Layers3 size={23}/></span>TradeOps<span className="brand-dot">.</span></a><span className="brand-caption">OPERATIONS WORKSPACE</span></SidebarHeader>
    <SidebarContent className="nav-content"><div className="workspace-label">WORKSPACE</div><SidebarMenu>{nav.map(n => <SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view === n.id} className="nav-item" onClick={() => {setView(n.id);setOpenMobile(false);}}><n.icon size={19}/><span>{n.title}</span>{n.id === 'exceptions' && count > 0 && <span className="nav-count">{count}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>
      <div className="sidebar-note"><span className="note-icon"><FlaskConical size={19}/></span><strong>Your operations sandbox</strong><p>Explore a trading desk with sample data. Changes last for this session.</p></div>
    </SidebarContent>
    <SidebarFooter className="profile-footer"><span className="avatar">AS</span><div><strong>Alpha Soumaré</strong><span>Portfolio workspace</span></div></SidebarFooter>
  </Sidebar>;
}

function SettlementChart({ trades }: { trades: Trade[] }) {
  const stats = summarize(trades);
  const samples = [0,.12,.26,.39,.51,.63,.74,1].map(r=>stats.rate*r);
  const chart = samples.map((y,i) => ({x:50+i*90, y:185-y*1.6}));
  const path = chart.map((p,i) => `${i ? 'L':'M'} ${p.x} ${p.y}`).join(' ');
  return <section className="panel chart-panel"><div className="panel-head"><div><h2>Settlement progress</h2><p>Current batch with an illustrative session curve</p></div><span className="subtle-pill">02 OCT</span></div><div className="chart-summary"><strong>{stats.rate.toFixed(1)}<span>%</span></strong><div><span className="positive">{stats.settled} of {stats.total} settled</span><small>Count-based completion</small></div></div>
    <div className="chart-wrap"><svg viewBox="0 0 720 230" role="img" aria-label={`${stats.settled} of ${stats.total} trades settled; illustrative session progress`}>
      <defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".16"/><stop offset="100%" stopColor="#2563eb" stopOpacity="0"/></linearGradient></defs>
      {[0,25,50,75,100].map(v => <g key={v}><line x1="50" y1={185-v*1.6} x2="688" y2={185-v*1.6} stroke="#edf0f5" strokeDasharray="4 5"/><text x="0" y={190-v*1.6} fill="#7c879a" fontSize="13">{v}%</text></g>)}
      <path d={`${path} L680 185 L50 185 Z`} fill="url(#area)"/><path d={path} fill="none" stroke="#2563eb" strokeWidth="3.5" strokeLinecap="round" strokeLinejoin="round"/>
      {chart.map((p,i) => <g key={i}><circle cx={p.x} cy={p.y} r={i===7?5:3} fill={i===7?'#2563eb':'white'} stroke="#2563eb" strokeWidth="2"/><text x={p.x} y="218" textAnchor="middle" fill="#7c879a" fontSize="13">{['09:00','09:30','10:00','10:30','11:00','11:30','12:00','12:40'][i]}</text></g>)}
    </svg><div className="mobile-chart-axis"><span>09:00</span><span>10:30</span><span>12:40 ET</span></div></div><div className="chart-foot"><span><i className="legend-line"/>Illustrative settlement curve</span><span>Current batch · USD</span></div>
  </section>;
}

function TradesTable({ trades, onSelect, compact = false }: { trades: Trade[]; onSelect: (t: Trade) => void; compact?: boolean }) {
  return <div className="table-scroll"><Table className="trade-table"><TableHeader><TableRow><TableHead>Trade / instrument</TableHead>{!compact && <TableHead>Counterparty</TableHead>}<TableHead>Side</TableHead><TableHead className="numeric">Notional</TableHead><TableHead>Status</TableHead>{!compact && <TableHead>Owner</TableHead>}<TableHead><span className="sr-only">Open details</span></TableHead></TableRow></TableHeader><TableBody>{trades.map(t => <TableRow key={t.id}><TableCell><button className="instrument-link" onClick={()=>onSelect(t)}><strong>{t.symbol}</strong><small>{t.id} · {t.desk}</small></button></TableCell>{!compact && <TableCell>{t.counterparty}</TableCell>}<TableCell><span className={`side-${t.side.toLowerCase()}`}>{t.side}</span></TableCell><TableCell className="numeric mono">{money(notional(t))}</TableCell><TableCell><Badge status={t.status}/></TableCell>{!compact && <TableCell>{t.owner}</TableCell>}<TableCell><button className="icon-button" aria-label={`View ${t.id}`} onClick={()=>onSelect(t)}><ChevronRight size={17}/></button></TableCell></TableRow>)}</TableBody></Table>{trades.length===0 && <div className="empty-state"><Search/><strong>No matching trades</strong><p>Try a different search or status.</p></div>}</div>;
}

export default function Home() {
  const [trades, setTrades] = useState<Trade[]>(seedTrades);
  const tradesRef = useRef(trades);
  const [view, setView] = useState<View>('overview');
  const [desk, setDesk] = useState('all');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('all');
  const [page, setPage] = useState(0);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [activity, setActivity] = useState(initialActivity);
  const [surge, setSurge] = useState(25);
  const [capacity, setCapacity] = useState(100);
  const [breakRate, setBreakRate] = useState(8);
  const [showMethod, setShowMethod] = useState(false);
  const scenario = simulate(64, surge, capacity, breakRate);
  const selected = trades.find(t => t.id === selectedId);
  const scope = trades.filter(t => desk==='all'||t.desk===desk);
  const stats = summarize(scope);
  const exceptions = scope.filter(isBreak).sort((a,b) => (a.priority==='High'?0:1)-(b.priority==='High'?0:1));
  const filtered = scope.filter(t => (status==='all'||t.status===status) && `${t.id} ${t.symbol} ${t.name} ${t.counterparty} ${t.owner}`.toLowerCase().includes(search.toLowerCase()));
  const pages = Math.max(1, Math.ceil(filtered.length/8));
  const visibleTrades = filtered.slice(page*8, page*8+8);
  useEffect(()=>{setPage(0);},[desk,status,search]);
  useEffect(()=>{if(page >= pages)setPage(pages-1);},[page,pages]);
  const advanceRef = useRef<(id: string) => Trade>(()=>{throw new Error('Not ready');});
  const advance = (id: string) => {
    const before = tradesRef.current.find(t=>t.id===id);
    if (!before) throw new Error('Trade not found.');
    const updated = transitionTrade(tradesRef.current,id);
    const after = updated.find(t=>t.id===id)!;
    tradesRef.current = updated;
    setTrades(updated);
    const text = after.status==='Settled' ? `${id} settled in the demo` : isBreak(before) ? `${id} exception cleared; trade matched` : `${id} matched in the demo`;
    const event: Activity = {id:`${id}-${Date.now()}`, text, time:'Now', type:after.status==='Settled'?'settlement':'match'};
    setActivity(a => [event,...a].slice(0,20));
    toast.success(text);
    return after;
  };
  advanceRef.current = advance;
  useEffect(()=>{
    type Tool = { name: string; title: string; description: string; inputSchema: object; annotations: object; execute: (input: unknown) => unknown };
    const ctx = (document as Document & {modelContext?: {registerTool: (t: Tool, o: {signal: AbortSignal})=>void|Promise<void>}}).modelContext;
    if (!ctx?.registerTool) return;
    const life = new AbortController();
    const toolset: Tool[] = [
      {name:'read_trade_operations',title:'Read sample trade operations',description:'Read the current sample trade statuses and KPIs without changing them.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Provide an empty object.');return {summary:summarize(tradesRef.current),trades:tradesRef.current.map(t=>({id:t.id,symbol:t.symbol,status:t.status,issue:t.issue??null}))};}},
      {name:'advance_sample_trade',title:'Advance a sample trade',description:'Clear a sample exception or match a pending trade; matched trades become settled. Only modifies this demo session.',inputSchema:{type:'object',properties:{tradeId:{type:'string'}},required:['tradeId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||typeof input!=='object'||Object.keys(input).length!==1||typeof (input as {tradeId?:unknown}).tradeId!=='string')throw new Error('Provide one tradeId string.');const trade=advanceRef.current((input as {tradeId:string}).tradeId);await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));return {id:trade.id,status:trade.status};}}
    ];
    toolset.forEach(tool=>{try{void Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}});
    return ()=>life.abort();
  },[]);
  function exportTrades() {
    const cols=['Trade ID','Instrument','Desk','Counterparty','Side','Quantity','Price','Notional USD','Status','Settlement','Owner'];
    const rows=filtered.map(t=>[t.id,t.symbol,t.desk,t.counterparty,t.side,t.quantity,t.price,notional(t).toFixed(2),t.status,t.settlement,t.owner]);
    const csv=[cols,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');
    const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='tradeops-sample-trades.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success(`${filtered.length} sample trades exported`);
  }
  function reset() { const next=seedTrades();tradesRef.current=next;setTrades(next);setActivity(initialActivity);setSelectedId(null);setSearch('');setStatus('all');setDesk('all');setPage(0);setSurge(25);setCapacity(100);setBreakRate(8);toast.success('Sample workspace reset'); }

  return <SidebarProvider style={{'--sidebar-width':'232px'} as CSSProperties}><AppNav view={view} setView={setView} count={trades.filter(isBreak).length}/><main className="main-workspace">
    <header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={14}/><strong>{nav.find(n=>n.id===view)?.title}</strong></div><div className="topbar-right"><span className="demo-badge"><FlaskConical size={13}/> Interactive demo</span><Tooltip><TooltipTrigger asChild><button className="icon-button" aria-label="Reset sample workspace" onClick={reset}><RotateCcw size={17}/></button></TooltipTrigger><TooltipContent>Reset this sample session</TooltipContent></Tooltip><span className="avatar small">AS</span></div></header>
    <div className="workspace-body"><div className="page-heading"><div><div className="eyebrow">NEW YORK · SAMPLE DESK</div><h1>{view==='overview'?'Operations overview':view==='trades'?'Trade blotter':view==='exceptions'?'Exception control': 'Stress simulator'}</h1><p>{view==='overview'?'A clear view of your trades, settlements, and next priorities.':view==='trades'?'Follow every sample trade from booking to settlement.':view==='exceptions'?'Prioritize breaks, investigate the cause, and get trades moving.':'Test the limits of your desk before the next volume spike.'}</p></div><div className="heading-actions">{view!=='simulator'&&<Select value={desk} onValueChange={setDesk}><SelectTrigger aria-label="Filter by desk" className="desk-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All desks</SelectItem><SelectItem value="Equities">Equities</SelectItem><SelectItem value="Fixed income">Fixed income</SelectItem><SelectItem value="ETFs">ETFs</SelectItem></SelectContent></Select>}{view==='trades'?<button className="button primary" onClick={exportTrades}><Download size={16}/>Export CSV</button>:view!=='simulator'?<span className="date-label"><Clock3 size={15}/>02 Oct · 12:40 ET</span>:<button className="button" onClick={()=>{setSurge(25);setCapacity(100);setBreakRate(8);}}><RotateCcw size={15}/>Reset scenario</button>}</div></div>

    {view==='overview'&&<><div className="metrics-grid"><Metric label="Gross trade notional" value={money(stats.gross)} icon={TrendingUp} detail={`${stats.total} trades in the sample batch`}/><Metric label="Settlement completion" value={`${stats.rate.toFixed(1)}%`} icon={CheckCircle2} detail={`${stats.settled} settled · ${stats.total-stats.settled} remaining`} positive/><Metric label="Open exceptions" value={String(stats.breaks).padStart(2,'0')} icon={TriangleAlert} detail={stats.breaks?'Review the exception queue':'All exceptions cleared'} warning={stats.breaks>0}/><Metric label="Exception notional" value={money(stats.risk)} icon={ShieldCheck} detail="Gross value of trades with breaks" warning={stats.breaks>0}/></div>
      <div className="overview-grid"><SettlementChart trades={scope}/><section className="priority-panel"><div className="priority-head"><span className="light-icon"><ShieldCheck size={20}/></span><span className="mini-label">DESK PRIORITIES</span></div><h2>{stats.breaks?`${stats.breaks} trades need\nyour attention.`:'Your exception queue\nis clear.'}</h2><p>{stats.breaks?`${money(stats.risk)} in sample notional is held in the exception queue. Start with the high-priority breaks.`:'No open breaks in this desk. Continue matching pending trades and settling ready records.'}</p><div className="priority-row"><span>High-priority breaks</span><strong>{exceptions.filter(t=>t.priority==='High').length}</strong></div><div className="priority-row"><span>Ready for settlement</span><strong>{scope.filter(t=>t.status==='Matched').length}</strong></div><button className="button priority-button" onClick={()=>setView('exceptions')}>Review exceptions</button><button className="priority-link" onClick={()=>setView('simulator')}><FlaskConical size={15}/>Explore a stress scenario</button></section></div>
      <div className="lower-grid"><section className="panel"><div className="panel-head"><div><h2>Trades to watch</h2><p>Exceptions and outstanding settlements</p></div><button className="text-button" onClick={()=>setView('trades')}>View all trades</button></div><TradesTable compact trades={scope.filter(t=>t.status!=='Settled').slice(0,5)} onSelect={t=>setSelectedId(t.id)}/></section><section className="panel activity-panel"><div className="panel-head"><div><h2>Desk activity</h2><p>Sample events and session actions</p></div><ActivityIcon size={18}/></div><div className="activity-list" aria-live="polite">{activity.slice(0,5).map(a=><div className="activity-item" key={a.id}><span className={`activity-icon ${a.type}`} >{a.type==='exception'?<TriangleAlert size={15}/>:<CheckCircle2 size={15}/>}</span><div><p>{a.text}</p><small>{a.time==='Now'?'Just now · this session':`${a.time} ET · sample event`}</small></div></div>)}</div></section></div>
    </>}

    {view==='trades'&&<section className="panel blotter-panel"><div className="table-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search trades" placeholder="Search trade, instrument, counterparty..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</div><div className="table-toolbar-right"><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Filter by trade status"><ListFilter size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{['Settled','Matched','Pending','Exception','Failed'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><span className="muted">{filtered.length} trades</span></div></div><TradesTable trades={visibleTrades} onSelect={t=>setSelectedId(t.id)}/><div className="pagination-footer"><span>{filtered.length?`${page*8+1}–${Math.min((page+1)*8,filtered.length)} of ${filtered.length} trades`:'0 trades'}</span><Pagination className="pagination-nav"><PaginationContent><PaginationItem><PaginationPrevious href="#" aria-disabled={page===0} onClick={e=>{e.preventDefault();if(page>0)setPage(page-1);}}/></PaginationItem><PaginationItem className="page-indicator">{page+1} / {pages}</PaginationItem><PaginationItem><PaginationNext href="#" aria-disabled={page===pages-1} onClick={e=>{e.preventDefault();if(page<pages-1)setPage(page+1);}}/></PaginationItem></PaginationContent></Pagination></div></section>}

    {view==='exceptions'&&<><div className="exception-summary"><div><TriangleAlert size={20}/><strong>{stats.breaks} open breaks</strong><span>· {money(stats.risk)} gross notional</span></div><span className="muted">Ordered by priority</span></div><div className="exception-grid">{exceptions.map(t=><section className="panel exception-card" key={t.id}><div className="exception-card-head"><span className={`priority-badge ${t.priority?.toLowerCase()}`}>{t.priority} priority</span><Badge status={t.status}/></div><h2>{t.issue}</h2><div className="exception-instrument"><strong>{t.symbol}</strong><span>{t.id} · {t.counterparty}</span></div><div className="exception-details"><div><small>Gross notional</small><strong>{money(notional(t))}</strong></div><div><small>Assigned to</small><strong>{t.owner}</strong></div></div><p className="next-action"><span>NEXT STEP</span>{t.action}</p><button className="button" onClick={()=>setSelectedId(t.id)}>Investigate trade<ChevronRight size={16}/></button></section>)}</div>{exceptions.length===0&&<section className="panel empty-state success-empty"><CheckCircle2 size={38}/><h2>No open exceptions</h2><p>Every break in this desk has been cleared.</p><button className="button" onClick={()=>setView('trades')}>Review trade blotter</button></section>}</>}

    {view==='simulator'&&<><div className="simulator-grid"><section className="panel scenario-controls"><div className="panel-head"><div><h2>Build a scenario</h2><p>Start with a baseline of 64 sample trades</p></div><FlaskConical size={21}/></div><div className="preset-row">{[{name:'Normal day',s:0,c:100,b:5},{name:'Volume spike',s:75,c:100,b:10},{name:'Lean team',s:25,c:50,b:8}].map(p=><button key={p.name} className={`preset ${surge===p.s&&capacity===p.c&&breakRate===p.b?'active':''}`} onClick={()=>{setSurge(p.s);setCapacity(p.c);setBreakRate(p.b);}}>{p.name}</button>)}</div><ScenarioSlider label="Volume increase" value={surge} min={0} max={100} suffix="%" hint="Additional trade flow above the baseline" onChange={setSurge}/><ScenarioSlider label="Processing capacity" value={capacity} min={20} max={150} suffix="%" hint="100% = capacity for 80 clean trades" onChange={setCapacity}/><ScenarioSlider label="Exception rate" value={breakRate} min={0} max={20} suffix="%" hint="Incoming trades that need manual review" onChange={setBreakRate}/><div className="model-note"><CircleHelp size={17}/><p>Illustrative capacity model. Exceptions stay open, and clean trades settle up to the available capacity.</p></div></section>
      <section className="scenario-result"><div className="result-kicker"><Sparkles size={17}/>PROJECTED OUTCOME</div><div className="result-main"><strong>{scenario.backlog}</strong><span>trades left in the backlog</span></div><div className="capacity-visual"><div style={{width:`${scenario.rate}%`}}/><span>{scenario.rate.toFixed(1)}% completion</span></div><div className="result-metrics"><div><span>Incoming</span><strong>{scenario.incoming}</strong></div><div><span>Capacity</span><strong>{scenario.capacity}</strong></div><div><span>Exceptions</span><strong>{scenario.exceptions}</strong></div></div><div className="scenario-insight"><h3>{scenario.utilization>100?'Capacity is the bottleneck.':scenario.exceptions>0?'Exceptions drive the remaining backlog.':'The desk can clear this workload.'}</h3><p>{scenario.utilization>100?`Clean trade flow exceeds capacity by ${Math.max(0,scenario.incoming-scenario.exceptions-scenario.capacity)} trades. Increase capacity or reduce incoming flow to test the impact.`:scenario.exceptions>0?`${scenario.exceptions} trades need manual review. Lower the exception rate to see how better upstream controls change completion.`:'Available capacity covers clean trade flow with no modeled exceptions.'}</p></div><button className="method-button" onClick={()=>setShowMethod(true)}><CircleHelp size={16}/>See model assumptions</button></section></div>
      <section className="panel scenario-comparison"><div className="panel-head"><div><h2>Workload breakdown</h2><p>Each incoming trade lands in one of three groups</p></div></div><div className="breakdown-grid">{[{label:'Settled in model',n:scenario.processed,color:'blue',desc:'Clean trades processed within capacity'},{label:'Capacity overflow',n:Math.max(0,scenario.incoming-scenario.exceptions-scenario.capacity),color:'orange',desc:'Clean trades above the processing limit'},{label:'Manual exceptions',n:scenario.exceptions,color:'red',desc:'Trades held for investigation'}].map(x=><div key={x.label}><div className="breakdown-label"><i className={x.color}/>{x.label}<strong>{x.n}</strong></div><Progress value={scenario.incoming?x.n/scenario.incoming*100:0} className={`breakdown-progress ${x.color}`}/><small>{x.desc}</small></div>)}</div></section>
    </>}
    <footer className="workspace-footer"><span>TradeOps · Built by Alpha Soumaré</span><span>Synthetic data · Session-only changes</span></footer></div>
  </main>

  <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelectedId(null);}}><SheetContent className="trade-sheet w-full sm:max-w-[480px] overflow-y-auto"><SheetHeader><div className="eyebrow">TRADE DETAILS</div><SheetTitle>{selected?.symbol}<span className="sheet-instrument-name">{selected?.name}</span></SheetTitle><SheetDescription>{selected?.id} · Sample settlement record</SheetDescription></SheetHeader>{selected&&<div className="sheet-body"><div className="sheet-status"><Badge status={selected.status}/><span className="muted">{selected.settlement}</span></div><Tabs defaultValue="details"><TabsList className="detail-tabs"><TabsTrigger value="details">Trade details</TabsTrigger><TabsTrigger value="lifecycle">Lifecycle</TabsTrigger></TabsList><TabsContent value="details"><dl className="trade-fields">{[['Counterparty',selected.counterparty],['Desk',selected.desk],['Side',selected.side],['Quantity',selected.quantity.toLocaleString()+(selected.desk==='Fixed income'?' par':' shares')],['Sample price',`$${selected.price.toFixed(2)}`+(selected.desk==='Fixed income'?' / $100 par':'')],['Gross notional',money(notional(selected))],['Currency','USD'],['Trade date','01 Oct 2026'],['Settlement date',selected.settlement],['Owner',selected.owner]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></TabsContent><TabsContent value="lifecycle"><div className="lifecycle"><div className="lifecycle-step complete"><CheckCircle2/><div><strong>Booked</strong><small>Trade captured in the sample batch</small></div></div>{flow.map((s,i)=><div key={s} className={`lifecycle-step ${selected.status==='Settled'||selected.status==='Matched'&&i<2||selected.status==='Pending'&&i===0?'complete':''}`}><CheckCircle2/><div><strong>{s}</strong><small>{s==='Pending'?'Awaiting matching checks':s==='Matched'?'Details aligned and ready to settle':'Cash and securities exchanged in the demo'}</small></div></div>)}{isBreak(selected)&&<div className="lifecycle-step break"><TriangleAlert/><div><strong>{selected.status}</strong><small>{selected.issue}</small></div></div>}</div></TabsContent></Tabs>
      {isBreak(selected)&&<div className="resolution-note"><TriangleAlert size={18}/><div><strong>{selected.issue}</strong><p>{selected.action}</p></div></div>}{selected.status==='Matched'&&<div className="ready-note"><CheckCircle2 size={17}/>Ready for a sample settlement</div>}
      {selected.status!=='Settled'?<button className="button primary action-button" onClick={()=>advance(selected.id)}><CheckCircle2 size={17}/>{isBreak(selected)?'Clear exception & match':selected.status==='Pending'?'Match sample trade':'Settle sample trade'}</button>:<div className="settled-note"><CheckCircle2/>This sample trade is settled.</div>}<p className="action-caption">Demo action only. No real trades or funds are affected.</p></div>}</SheetContent></Sheet>

  <Sheet open={showMethod} onOpenChange={setShowMethod}><SheetContent className="w-full sm:max-w-[480px] overflow-y-auto"><SheetHeader><SheetTitle>Model assumptions</SheetTitle><SheetDescription>A transparent model for exploring processing capacity.</SheetDescription></SheetHeader><div className="sheet-body method-content"><h3>How the projection works</h3><p>Incoming trades = 64 × (1 + volume increase). Processing capacity = 80 × capacity percentage.</p><p>Exceptions = incoming trades × exception rate. Clean trades = incoming trades − exceptions. Settled trades are the smaller of clean trades and processing capacity.</p><p>Backlog = incoming trades − settled trades. Counts round to whole trades. The model does not simulate cash, inventory, market prices, or actual settlement infrastructure.</p><h3>Trade data</h3><p>All prices, events, and operational records in this app are synthetic. Clearing a break moves a trade to Matched; settlement is a separate sample action.</p><h3>Settlement context</h3><p>The sample securities are booked on 01 October and due on 02 October. Most US broker-dealer securities transactions follow a one-business-day settlement cycle, with exceptions.</p><a href="https://www.sec.gov/investment/settlement-cycle-small-entity-compliance-guide-15c6-1-15c6-2-204-2" target="_blank" rel="noreferrer" className="source-link">SEC settlement-cycle guidance <ArrowUpRight size={15}/></a></div></SheetContent></Sheet>
  <Toaster position="bottom-right" theme="light" richColors/>
  </SidebarProvider>;
}

function Metric({ label,value,icon:Icon,detail,positive,warning }: { label:string; value:string; icon:typeof TrendingUp; detail:string; positive?:boolean;warning?:boolean }) { return <section className="metric-card"><div className="metric-top"><span>{label}</span><Icon size={17}/></div><strong className="metric-value">{value}</strong><div className={`metric-detail ${positive?'positive':warning?'warning':''}`}>{positive?<CheckCircle2 size={13}/>:warning?<TriangleAlert size={13}/>:<span className="metric-tick"/>}{detail}</div></section>; }
function ScenarioSlider({label,value,min,max,suffix,hint,onChange}:{label:string;value:number;min:number;max:number;suffix:string;hint:string;onChange:(n:number)=>void}) { return <div className="scenario-slider"><div><label>{label}</label><strong>{value}{suffix}</strong></div><Slider aria-label={label} value={[value]} min={min} max={max} step={1} onValueChange={v=>onChange(v[0])}/><p>{hint}</p></div>; }
