export type LearningLevel = 'beginner' | 'intermediate' | 'advanced';
export type WorkspaceView = 'overview' | 'trades' | 'exceptions' | 'simulator' | 'learning';
export type Concept = { id: string; term: string; meaning: string; example: string; role: string; related: string[]; source?: string };
export type Question = { id: string; prompt: string; choices: string[]; answer: number; explanations: string[]; hint: string; skill: string };
export type Exercise = { kind: 'notional' | 'lifecycle' | 'settlement' | 'matching' | 'reconciliation' | 'exceptions' | 'controls' | 'cutoff'; title: string; brief: string; hint: string; stages: number };
export type Lesson = { id: string; title: string; level: LearningLevel; minutes: number; summary: string; terms: string[]; points: { title: string; text: string }[]; flow: string[]; exercise: Exercise; questions: Question[]; badge: string; workspace: WorkspaceView; sources: string[] };

export const SOURCES = {
  settlement: { title: 'SEC Investor.gov: the T+1 settlement cycle', url: 'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/new-t1-settlement-cycle-what-investors-need-know-investor-bulletin' },
  matching: { title: 'DTCC: confirmation, matching, and affirmation', url: 'https://www.dtcc.com/insights/2024/trade-affirmations-key-questions-answered-as-t1-approaches' },
};

export const CONCEPTS: Concept[] = [
  { id:'trade', term:'Trade', meaning:'An agreement to buy or sell a financial instrument at an agreed price.', example:'A client buys 100 shares at $50 per share. Operations checks that the records and delivery arrangements reflect that agreement.', role:'A trader executes the transaction; an operations analyst helps process it accurately afterward.', related:['notional','matching','settlement'] },
  { id:'equity', term:'Stock / equity', meaning:'A share represents a small ownership interest in a company.', example:'In a simulated purchase of 100 AAPL shares, the security being delivered is stock.', role:'Check the instrument, share quantity, price, and account on the trade record.', related:['trade','bond','etf'] },
  { id:'bond', term:'Bond', meaning:'A debt security: an issuer borrows money and agrees to its repayment terms.', example:'A bond quoted at 98 means $98 for each $100 of face value. $100,000 face value has a quoted value of $98,000, before items such as accrued interest.', role:'Know whether quantity means shares or face value; the calculation changes.', related:['equity','notional'] },
  { id:'etf', term:'ETF', meaning:'An exchange-traded fund holds a portfolio of assets and trades on an exchange.', example:'A sample SPY trade represents ETF shares, rather than an individual stock.', role:'Record the correct instrument and share quantity, just as carefully as for other securities.', related:['equity','trade'] },
  { id:'counterparty', term:'Counterparty', meaning:'The other party to a transaction.', example:'Your desk buys shares from Meridian Securities in this fictional trade.', role:'Compare records with the other party and route discrepancies to the right contact.', related:['matching','confirmation'] },
  { id:'notional', term:'Notional', meaning:'The reference value of a trade. In these stock examples, it is quantity multiplied by price.', example:'100 shares × $50 = $5,000. That is trade value, not profit and not a prediction of loss.', role:'Use trade size to understand workload and prioritize investigations alongside deadlines and other risks.', related:['trade','bond','risk'] },
  { id:'matching', term:'Trade matching', meaning:'Checking that both sides record the same agreed trade details.', example:'Your record says 500 shares; the counterparty says 550. Investigate the quantity difference before treating the trade as matched.', role:'Compare instrument, side, quantity, price, dates, and account details.', related:['confirmation','affirmation','exception'], source:'matching' },
  { id:'confirmation', term:'Confirmation', meaning:'A record of the details of an executed transaction sent for checking.', example:'A broker sends the instrument, quantity, price, and settlement details for a purchase.', role:'Review the details against the agreed transaction and raise a break if they differ.', related:['matching','affirmation'], source:'matching' },
  { id:'affirmation', term:'Affirmation', meaning:'Acknowledging that a broker’s trade details agree with the institutional customer’s records.', example:'A buy-side firm or its custodian checks the broker’s confirmation and agrees to it.', role:'Complete the required post-trade checks promptly. Matching and affirmation do not mean cash and securities have already moved.', related:['matching','settlement','cutoff'], source:'matching' },
  { id:'settlement', term:'Settlement', meaning:'The transfer of securities to the buyer and cash to the seller.', example:'The buyer receives 20 shares and the seller receives $2,000 in a simulated $100-per-share trade.', role:'Check the due date, funding, securities availability, and instructions. Confirm the actual settlement status.', related:['t1','funding','dvp'], source:'settlement' },
  { id:'t1', term:'T+1', meaning:'A settlement date one business day after the trade date for transactions covered by that cycle.', example:'A covered US stock trade on Monday is normally due Tuesday, assuming neither is a holiday. A Friday trade is normally due Monday, if Monday is a business day.', role:'Plan with business days and the applicable market calendar. Other instruments and transactions can have different cycles.', related:['settlement','cutoff'], source:'settlement' },
  { id:'funding', term:'Funding', meaning:'Having the required cash available when a payment is due.', example:'A $2,000 purchase with only $1,500 available has a $500 cash shortfall.', role:'Raise the shortfall with the appropriate funding team; changing a status alone does not supply cash.', related:['settlement','exception','risk'] },
  { id:'dvp', term:'Delivery versus payment', meaning:'A settlement arrangement that links securities delivery to payment.', example:'The simplified practice ticket releases the shares and cash together after its readiness checks.', role:'Understand the market’s settlement arrangements. This training animation is not connected to a real settlement system.', related:['settlement','funding','risk'] },
  { id:'reconciliation', term:'Reconciliation', meaning:'Comparing records from different sources to find and explain differences.', example:'Your ledger shows 1,000 shares; a custody record shows 950. The 50-share difference needs investigation.', role:'Check timing, bookings, and supporting evidence. Do not overwrite a record merely to make totals agree.', related:['custodian','exception','controls'] },
  { id:'custodian', term:'Custodian', meaning:'An institution that holds assets and performs related services for its clients.', example:'A custody record shows the securities held in a sample account.', role:'Use the relevant custody and settlement records to investigate holdings and delivery differences.', related:['reconciliation','settlement'] },
  { id:'exception', term:'Exception / break', meaning:'A record or process that needs investigation because an expected check did not pass.', example:'A quantity mismatch or missing confirmation enters the exception queue.', role:'Find the cause, verify the correction, record the evidence, and monitor the next step.', related:['reconciliation','ssi','fail'] },
  { id:'fail', term:'Settlement fail', meaning:'A transaction that has not settled by its required settlement date.', example:'The seller cannot deliver the securities on the due date, so the trade needs follow-up.', role:'Identify the cause, assign an owner, escalate when needed, and track delivery. Missing a processing cutoff alone is not necessarily a settlement fail.', related:['exception','cutoff','settlement'], source:'matching' },
  { id:'ssi', term:'Settlement instructions / SSI', meaning:'The account and delivery details used to route cash or securities. SSI means standing settlement instructions.', example:'A fictional ticket points to ACCT-041, but its approved reference is ACCT-014.', role:'Validate changes through approved sources and review controls. A familiar-looking email is not sufficient evidence.', related:['exception','controls','settlement'] },
  { id:'controls', term:'Risk controls', meaning:'Checks and procedures designed to prevent, detect, and address problems.', example:'In the training desk, one analyst verifies instructions and a different reviewer approves the change.', role:'Use the firm’s actual policies. The lessons’ two-person checks and escalation thresholds are illustrative training rules.', related:['risk','ssi','reconciliation'] },
  { id:'risk', term:'Operational risk', meaning:'The risk of problems arising from processes, people, systems, or external events.', example:'A duplicated booking or an unverified account change can cause an operational problem even if market prices do not move.', role:'Prioritize using deadlines, trade size, uncertainty, and the impact of a failed control. Gross exception notional is not a loss estimate.', related:['controls','exception','capacity'] },
  { id:'cutoff', term:'Cutoff / deadline', meaning:'The time by which a particular processing step needs to be completed.', example:'The practice desk has a fictional 16:00 handoff deadline; a funding break due today needs prompt attention.', role:'Check the correct market and process deadline, time zone, and escalation route. A missed cutoff may require a different workflow; it is not automatically a settlement fail.', related:['t1','fail','controls'], source:'matching' },
  { id:'capacity', term:'Processing capacity', meaning:'How much work a desk can process over a given period.', example:'If 112 trades arrive but capacity covers 80 clean trades, extra work remains in the model.', role:'Plan staffing and reduce avoidable breaks. More capacity does not resolve incorrect records or missing cash by itself.', related:['risk','exception','controls'] },
];

const q = (id:string, prompt:string, choices:string[], answer:number, explanations:string[], hint:string, skill:string): Question => ({id,prompt,choices,answer,explanations,hint,skill});

export const LESSONS: Lesson[] = [
  {
    id:'markets', title:'Markets, in plain English', level:'beginner', minutes:5, summary:'Learn what is traded, who is involved, and what operations does.', terms:['trade','equity','bond','etf','counterparty','notional'],
    points:[{title:'Start with an agreement',text:'A buyer and seller agree on an instrument, quantity, and price. Stocks, bonds, and ETFs are different instruments.'},{title:'Separate execution from processing',text:'Sales and trading teams help arrange and execute transactions. Operations checks the records and helps the agreed transaction move through its post-trade steps.'},{title:'Make the numbers meaningful',text:'For a stock, shares × price gives trade notional. A large notional does not tell you profit, loss, or whether the trade is safe.'}], flow:['Buyer & seller','Agreed trade','Operations checks','Cash & securities'],
    exercise:{kind:'notional',title:'Read your first trade ticket',brief:'A fictional client buys 100 shares of NOVA at $50 each. Find its stock trade value, then identify the operations task.',hint:'Multiply 100 shares by $50. Operations checks the transaction; it does not choose the client’s investment.',stages:2},
    questions:[q('role','What is the operations analyst checking after execution?',['Whether the stock price will rise','That records and delivery arrangements reflect the agreed trade','Which company the client should buy'],1,['That is a market view, not a post-trade check.','Correct. Operations helps process the agreed transaction accurately.','Choosing an investment is different from processing an executed trade.'],'Think about accuracy and delivery, rather than an investment recommendation.','Operations role'),q('value','100 shares at $50 has a $5,000 notional. What does that mean?',['The trade’s reference value','A guaranteed $5,000 profit','An expected $5,000 loss'],0,['Correct. This example uses shares multiplied by price.','Trade value is not profit; profit depends on other information.','Notional alone is not a loss forecast.'],'Notional describes size.','Trade value'),q('party','What is a counterparty?',['The screen showing the trade','The other party to the transaction','The person approving your holiday'],1,['A screen is a tool; the counterparty is a transaction participant.','Correct. It is the other party on the trade.','That person is not necessarily involved in the transaction.'],'A trade has two sides.','Terminology')], badge:'Market explorer', workspace:'trades', sources:[],
  },
  {
    id:'lifecycle',title:'Follow a trade’s journey',level:'beginner',minutes:6,summary:'Move a sample trade from booking through matching to settlement.',terms:['trade','matching','confirmation','affirmation','settlement'],
    points:[{title:'Capture the executed trade',text:'Record what was agreed: instrument, side, quantity, price, account, and dates. Institutional flows may also allocate a trade across client accounts.'},{title:'Agree the details',text:'Compare the relevant records and complete the required confirmation and affirmation workflow. Investigate a discrepancy rather than forcing a match.'},{title:'Prepare, then confirm delivery',text:'Matching is agreement about details. Settlement is delivery of securities and payment. In this simplified map, readiness checks sit between those steps.'}],flow:['Book','Match / affirm','Check readiness','Settle'],
    exercise:{kind:'lifecycle',title:'Take NOVA from booked to settled',brief:'Both parties agree to 20 shares at $100. The practice ticket is booked; work through its checks in the right order.',hint:'Agree the trade details first. Then verify cash and securities before completing simulated delivery.',stages:3},
    questions:[q('sequence','The trade is matched. Has it necessarily settled?',['Yes, they mean the same thing','No, cash and securities still need to move','Yes, if its notional is small'],1,['Matching confirms agreement; it does not confirm delivery.','Correct. These are separate milestones.','Size does not turn agreement into delivery.'],'Compare “agree the details” with “transfer the assets.”','Lifecycle'),q('booking','Which booking is useful for matching?',['Instrument, quantity, price, account, and dates','Only the trader’s name','Only a green status label'],0,['Correct. Matching requires the actual transaction details.','A name alone does not identify all agreed terms.','A status label is not evidence that the details agree.'],'Think about what both parties need to compare.','Booking accuracy'),q('break','The two sides disagree on quantity. What comes next?',['Settle anyway','Investigate the source of the difference','Hide the counterparty record'],1,['A quantity difference should be investigated before proceeding.','Correct. Understand the break and verify any correction.','Hiding a record removes evidence without resolving the problem.'],'A clean process explains differences.','Exception handling')],badge:'Lifecycle navigator',workspace:'trades',sources:['matching','settlement'],
  },
  {
    id:'settlement',title:'Settlement: cash meets securities',level:'beginner',minutes:6,summary:'Understand T+1, cash readiness, and why matched is not settled.',terms:['settlement','t1','funding','dvp','fail'],
    points:[{title:'Know what moves',text:'The buyer receives the securities and the seller receives the cash. Matching alone does not make either transfer happen.'},{title:'Use the correct calendar',text:'Covered US securities transactions generally use T+1: one business day after trade date. Weekends, market holidays, and exceptions matter.'},{title:'Check readiness',text:'Confirm the required cash, available securities, instructions, and delivery status. The practice exercise simplifies these checks into a small ticket.'}],flow:['Matched trade','Cash + stock ready','Simulated exchange','Settled'],
    exercise:{kind:'settlement',title:'Resolve a cash shortfall',brief:'Buy 20 NOVA shares at $100. The buyer has $1,500; the seller has all 20 shares. Find the missing cash before settling.',hint:'The purchase needs $2,000. Compare that amount with the $1,500 available; do not release an unfunded ticket.',stages:3},
    questions:[q('calendar','A covered US stock trade executes Friday. Monday is a business day. When is its normal T+1 date?',['Saturday','Monday','The following Friday'],1,['T+1 counts business days, so Saturday is not the next business day.','Correct. Monday is the next business day in this example.','That is later than the normal cycle in this example.'],'Skip the weekend.','Settlement calendar'),q('cash','A $2,000 trade has only $1,500 available. What is missing?',['$500 of cash','500 shares','Nothing, because it is matched'],0,['Correct. $2,000 minus $1,500 is a $500 shortfall.','The difference here is cash, not share quantity.','Matching does not fund the purchase.'],'Compare required cash with available cash.','Funding'),q('delivery','What evidence supports a Settled status?',['The cash and securities transfers completed','A matching check passed','A user clicked a status label'],0,['Correct. Actual delivery and payment support settlement.','Matching supports agreement, not delivery.','A label change alone is not settlement evidence.'],'Look for the actual transfer outcome.','Settlement evidence')],badge:'Settlement starter',workspace:'trades',sources:['settlement'],
  },
  {
    id:'matching',title:'Match the trade details',level:'intermediate',minutes:6,summary:'Compare bookings with confirmations and investigate a quantity break.',terms:['matching','confirmation','affirmation','counterparty'],
    points:[{title:'Compare like with like',text:'Check that the records refer to the same instrument, direction, quantity, price, account, and settlement date.'},{title:'Use verified evidence',text:'A difference does not tell you which record is wrong. Confirm the agreed terms before correcting anything.'},{title:'Distinguish agreement from delivery',text:'Confirmation records the transaction. Affirmation acknowledges agreement in an institutional workflow. Settlement happens through the applicable delivery process.'}],flow:['Booking','Compare confirmation','Verify correction','Match / affirm'],
    exercise:{kind:'matching',title:'Find the 50-share mismatch',brief:'Your booking and the approved execution record show 500 NOVA shares. The confirmation shows 550. Compare the fields and record the verified quantity.',hint:'The quantity field differs. This scenario gives an approved execution record for 500 shares, so use that evidence to request a corrected confirmation.',stages:2},
    questions:[q('field','Booking: 500 shares at $100. Confirmation: 550 shares at $100. Which field differs?',['Price','Quantity','Instrument'],1,['Both records show $100, so price agrees.','Correct. 550 versus 500 is a quantity mismatch.','Both records refer to the same instrument in this example.'],'Compare the numbers one field at a time.','Matching'),q('evidence','Two records disagree. Which approach is sound?',['Always copy the counterparty','Verify the executed terms and correct the inaccurate record','Average the two quantities'],1,['The counterparty record can also contain an error.','Correct. Establish the agreed terms before correcting a record.','An average invents a quantity that might not have been traded.'],'Find an approved source for what was executed.','Evidence handling'),q('affirm','Affirmation in the institutional workflow means:',['The securities have already arrived','Acknowledging that the broker’s trade details agree with the customer’s records','The trade is profitable'],1,['Agreement and delivery are separate.','Correct. It acknowledges agreement on the transaction details.','Affirmation does not measure profit.'],'Think about agreement on the confirmation.','Affirmation')],badge:'Matching investigator',workspace:'trades',sources:['matching'],
  },
  {
    id:'reconciliation',title:'Reconciliation: find the difference',level:'intermediate',minutes:7,summary:'Compare an internal ledger and a custody record without losing evidence.',terms:['reconciliation','custodian','exception','controls'],
    points:[{title:'Compare two sources',text:'Use the same instrument, account, date, and units. A share balance is not directly comparable with a dollar value.'},{title:'Explain the break',text:'A difference may reflect timing, an incorrect booking, an incomplete delivery, or another event. Keep both records and investigate.'},{title:'Close with evidence',text:'Document the explanation and verified outcome. Matching the displayed totals without evidence is not a completed reconciliation.'}],flow:['Internal record','External record','Investigate difference','Document outcome'],
    exercise:{kind:'reconciliation',title:'Investigate a custody difference',brief:'The same sample account shows 1,000 NOVA shares internally and 950 in custody. Identify the difference, then choose an evidence-led next step.',hint:'1,000 minus 950 is 50 shares. Investigate timing and delivery records before changing either source.',stages:2},
    questions:[q('difference','Internal holdings: 1,000. Custody holdings: 950. What is the difference?',['$50','50 shares','There is no difference'],1,['These are share quantities, not cash values.','Correct. The share difference is 50.','The two balances do not agree.'],'Keep the units as shares.','Reconciliation'),q('close','What is enough to close a reconciliation break?',['Make the numbers equal without an explanation','Document the cause and verify the resulting records','Delete the old record'],1,['Equal totals can hide an unresolved error.','Correct. Closure needs an explained, verified outcome.','Deleting evidence does not resolve the break.'],'You need evidence, not only matching totals.','Evidence handling'),q('timing','Could a timing difference explain a reconciliation break?',['Yes; verify it using the relevant records','No; every difference is fraud','Yes; so no investigation is needed'],0,['Correct. Timing is one possible cause, but it must be checked.','Do not jump to a cause without evidence.','A possible explanation still needs verification.'],'A cause is a hypothesis until you verify it.','Investigation')],badge:'Reconciliation detective',workspace:'exceptions',sources:[],
  },
  {
    id:'exceptions',title:'Resolve an exception safely',level:'intermediate',minutes:7,summary:'Investigate a routing mismatch, use approved instructions, and keep an audit trail.',terms:['exception','ssi','controls','fail'],
    points:[{title:'Describe the problem',text:'Record the affected trade, discrepancy, due date, impact, and owner. Priority is more useful when you can explain it.'},{title:'Validate the correction',text:'Use an approved reference. In this training desk, instruction changes require independent review before release.'},{title:'Monitor the next step',text:'Clearing an exception is not the same as settlement. Track the trade until the intended downstream outcome is confirmed.'}],flow:['Identify break','Verify source','Review change','Monitor trade'],
    exercise:{kind:'exceptions',title:'Correct a settlement route',brief:'The sample ticket uses ACCT-041. The approved reference says ACCT-014. An email asks you to release it immediately.',hint:'Use the approved instruction reference and an independent reviewer. The urgent email does not replace those controls.',stages:2},
    questions:[q('source','What supports an instruction change in this training desk?',['An urgent email alone','The approved reference and independent review','The quickest-looking account number'],1,['Urgency does not verify destination details.','Correct. The scenario requires a verified source and separate review.','Appearance is not evidence.'],'Check the stated training controls.','Instruction controls'),q('priority','Which break usually needs earlier attention, all else equal?',['A due-today delivery problem with high impact','A routine note for next month','A completed trade with no break'],0,['Correct. Deadline and impact guide triage.','A later routine note is less urgent in this comparison.','There is no open delivery problem on that ticket.'],'Use deadline and impact together.','Prioritization'),q('cleared','You have cleared an exception. What must you still monitor?',['The next processing and settlement outcome','Nothing, every cleared exception is settled','Only the chart color'],0,['Correct. Resolve the cause, then confirm the downstream result.','A matched trade can still be waiting for delivery.','A chart color is not delivery evidence.'],'The process continues after the break is cleared.','Lifecycle')],badge:'Exception resolver',workspace:'exceptions',sources:[],
  },
  {
    id:'controls',title:'Risk controls under pressure',level:'advanced',minutes:8,summary:'Handle an urgent instruction change without bypassing verification or review.',terms:['risk','controls','ssi','cutoff'],
    points:[{title:'Separate operational and market risk',text:'A wrong account or duplicated booking is a process problem. A price move is a different kind of risk. Notional alone estimates neither loss.'},{title:'Respect control boundaries',text:'This practice desk requires a verified source, a different reviewer, and a recorded reason for changes. Actual firms define their own controls.'},{title:'Escalate with useful facts',text:'Explain the trade, deadline, uncertain detail, impact, owner, and next action. Time pressure increases the need for a clear handoff.'}],flow:['Detect uncertainty','Hold release','Independent review','Document + escalate'],
    exercise:{kind:'controls',title:'Handle an urgent account change',brief:'An analyst edits a destination account, then asks to approve their own change because the fictional cutoff is close.',hint:'In this training desk, the person changing instructions cannot independently review their own change. Hold release and request another reviewer.',stages:2},
    questions:[q('review','Why ask a different reviewer to check an instruction change?',['To add a second independent check','To guarantee the market price','To avoid documenting the change'],0,['Correct. Independent review can detect an error the first person missed.','A review does not control market prices.','Review and documentation support each other.'],'The reviewer checks the work independently.','Independent review'),q('notionalrisk','Gross exception notional is $10 million. Does that prove a $10 million loss?',['Yes','No; it measures affected trade value, not realized or expected loss','Only if the chart is red'],1,['Notional is not a loss calculation.','Correct. Assess the actual circumstances and exposure separately.','Color is not a financial loss measure.'],'Trade size and loss are different quantities.','Risk interpretation'),q('escalate','A useful escalation includes:',['Only “urgent”','The trade, deadline, impact, owner, and requested action','A screenshot with no explanation'],1,['Urgency alone does not tell the recipient what to do.','Correct. These facts support a clear and actionable handoff.','A screenshot alone can omit the deadline and needed action.'],'Help the next person understand the problem and act.','Escalation')],badge:'Control guardian',workspace:'exceptions',sources:[],
  },
  {
    id:'cutoff',title:'Run the cutoff desk',level:'advanced',minutes:8,summary:'Triage a mixed queue, protect controls, and make a clear time-sensitive handoff.',terms:['cutoff','funding','fail','capacity','risk'],
    points:[{title:'Sort by consequence and time',text:'A due-today funding problem can outrank a larger routine record due later. Use the deadline, current status, impact, and uncertainty together.'},{title:'Choose a specific response',text:'Assign the issue to the right team, request the missing action, and retain a named owner. More staffing does not automatically fix missing cash.'},{title:'Keep the status honest',text:'Escalated means help has been requested; it does not mean settled. A missed processing cutoff can require another route, rather than automatically becoming a settlement fail.'}],flow:['Triage queue','Assign owner','Escalate blocker','Track outcome'],
    exercise:{kind:'cutoff',title:'The last two minutes',brief:'Your fictional desk handoff is approaching. Choose which ticket needs attention first, then route its blocker. Optional timed practice is available.',hint:'Look for the high-impact ticket due today with an unresolved cash shortfall. Send funding to Treasury and keep the release on hold.',stages:2},
    questions:[q('triage','Which ticket deserves the first investigation in this queue?',['A $250,000 funding break due today','A $20,000 quantity query due tomorrow','A trade already settled with no issue'],0,['Correct. Its deadline and unresolved funding make it the first priority in this scenario.','This ticket still needs follow-up, but it has more time in this scenario.','It has no open issue requiring this immediate investigation.'],'Compare both the deadline and the blocker.','Prioritization'),q('capacityfix','Which problem is not fixed merely by adding processing capacity?',['A missing cash allocation','A workload bottleneck','Too many clean trades for available staff'],0,['Correct. The funding team still needs to address the missing cash.','Capacity can help with a workload bottleneck.','More processing capacity can help handle clean trade volume.'],'People and processing power do not create the required funding.','Risk controls'),q('deadline','Missing a processing cutoff always means a settlement fail. True or false?',['True','False; a different processing route may still achieve settlement','True, but only for small trades'],1,['A cutoff and the required settlement date are distinct.','Correct. Check the process and delivery outcome instead of assuming a fail.','Trade size does not make this blanket statement correct.'],'Distinguish the process deadline from the settlement outcome.','Cutoff handling')],badge:'Cutoff captain',workspace:'simulator',sources:['matching'],
  },
];

export type QuizAttempt = { choice: number; correct: boolean; firstCorrect: boolean; attempts: number };
export type PracticeState = { stage: number; input: string; checks: string[] };
export type LessonProgress = { section: number; practice: PracticeState; answers: Record<string,QuizAttempt>; completed: boolean; bestScore: number | null; lastScore: number | null };
export type LearningProgress = { version: 1; level: LearningLevel; tour: {status:'new'|'active'|'skipped'|'complete'; step:number}; lessons: Record<string,LessonProgress>; lastLesson: string | null };
export const STORAGE_KEY = 'tradeops.learning.v1';
export const emptyPractice = (): PracticeState => ({stage:0,input:'',checks:[]});
export const emptyLesson = (): LessonProgress => ({section:0,practice:emptyPractice(),answers:{},completed:false,bestScore:null,lastScore:null});
export const emptyProgress = (): LearningProgress => ({version:1,level:'beginner',tour:{status:'new',step:0},lessons:{},lastLesson:null});
const bounded = (x:unknown,max:number) => typeof x==='number' && Number.isFinite(x) ? Math.max(0,Math.min(max,Math.floor(x))) : 0;
const scoreValue = (x:unknown) => typeof x==='number' && Number.isFinite(x) ? bounded(x,100) : null;

export function parseProgress(raw:string|null):LearningProgress {
  const blank=emptyProgress();
  if(!raw || raw.length>80000) return blank;
  try {
    const x=JSON.parse(raw);
    if(!x || x.version!==1) return blank;
    const level:LearningLevel=['beginner','intermediate','advanced'].includes(x.level)?x.level:'beginner';
    const tourStatus=['new','active','skipped','complete'].includes(x.tour?.status)?x.tour.status:'new';
    const lessons:Record<string,LessonProgress>={};
    for(const lesson of LESSONS){
      const lp=x.lessons?.[lesson.id]; if(!lp || typeof lp!=='object') continue;
      const answers:Record<string,QuizAttempt>={};
      for(const question of lesson.questions){
        const a=lp.answers?.[question.id];
        if(!a || typeof a.choice!=='number' || !Number.isInteger(a.choice) || a.choice<0 || a.choice>=question.choices.length) continue;
        answers[question.id]={choice:a.choice,correct:a.choice===question.answer,firstCorrect:a.firstCorrect===true&&a.choice===question.answer,attempts:Math.max(1,bounded(a.attempts,999))};
      }
      const practice={stage:bounded(lp.practice?.stage,lesson.exercise.stages),input:typeof lp.practice?.input==='string'?lp.practice.input.slice(0,100):'',checks:Array.isArray(lp.practice?.checks)?lp.practice.checks.filter((s:unknown):s is string=>typeof s==='string' && ['cash','stock','source','reviewer','audit'].includes(s)).slice(0,5):[]};
      const bestScore=scoreValue(lp.bestScore),lastScore=scoreValue(lp.lastScore);
      // Completion records an earned badge, including while a learner retakes a quiz.
      const completed=lp.completed===true && practice.stage===lesson.exercise.stages && bestScore!==null;
      const unlocked=completed?3:practice.stage===lesson.exercise.stages?2:1;
      lessons[lesson.id]={section:Math.min(bounded(lp.section,3),unlocked),practice,answers,completed,bestScore,lastScore};
    }
    return {version:1,level,tour:{status:tourStatus,step:bounded(x.tour?.step,5)},lessons,lastLesson:LESSONS.some(l=>l.id===x.lastLesson)?x.lastLesson:null};
  }catch{return blank;}
}

export function quizScore(lesson:Lesson, lp:LessonProgress):number {
  return Math.round(100*lesson.questions.filter(q=>lp.answers[q.id]?.firstCorrect).length/lesson.questions.length);
}
export function canComplete(lesson:Lesson,lp:LessonProgress):boolean {
  return lp.practice.stage===lesson.exercise.stages && lesson.questions.every(q=>lp.answers[q.id]?.correct);
}
export function recordAnswer(lesson:Lesson,lp:LessonProgress,questionId:string,choice:number):LessonProgress {
  const question=lesson.questions.find(q=>q.id===questionId);
  if(!question || !Number.isInteger(choice) || choice<0 || choice>=question.choices.length) return lp;
  const old=lp.answers[questionId]; if(old?.correct) return lp;
  const correct=choice===question.answer;
  return {...lp,answers:{...lp.answers,[questionId]:{choice,correct,firstCorrect:old?old.firstCorrect:correct,attempts:(old?.attempts??0)+1}}};
}
export function completeLesson(lesson:Lesson,lp:LessonProgress):LessonProgress {
  if(!canComplete(lesson,lp)) return lp;
  const score=quizScore(lesson,lp);
  return {...lp,section:3,completed:true,lastScore:score,bestScore:Math.max(lp.bestScore??0,score)};
}
export function recommendLesson(progress:LearningProgress):{lesson:Lesson;reason:string} {
  const resume=progress.lastLesson && LESSONS.find(l=>l.id===progress.lastLesson && progress.lessons[l.id] && (!progress.lessons[l.id].completed || progress.lessons[l.id].section===2&&!canComplete(l,progress.lessons[l.id])));
  if(resume)return {lesson:resume,reason:'Continue the tutorial you started. Your exercise and quiz checkpoints are saved.'};
  const review=LESSONS.filter(l=>progress.lessons[l.id]?.completed && (progress.lessons[l.id].bestScore??100)<70).sort((a,b)=>(progress.lessons[a.id].bestScore??0)-(progress.lessons[b.id].bestScore??0))[0];
  if(review)return {lesson:review,reason:`Review ${review.title.toLowerCase()}: your best first-attempt quiz score is ${progress.lessons[review.id].bestScore}%.`};
  const next=LESSONS.find(l=>l.level===progress.level && !progress.lessons[l.id]?.completed) ?? LESSONS.find(l=>!progress.lessons[l.id]?.completed);
  if(next)return {lesson:next,reason:`A next step for your ${progress.level} path. All other tutorials are available too.`};
  return {lesson:LESSONS[7],reason:'You finished every tutorial. Try an independent case or retake a quiz to sharpen your skills.'};
}
export function feedbackFor(lesson:Lesson,lp:LessonProgress):{strengths:string[];improve:string[]} {
  return {strengths:[...new Set(lesson.questions.filter(q=>lp.answers[q.id]?.firstCorrect).map(q=>q.skill))],improve:[...new Set(lesson.questions.filter(q=>lp.answers[q.id] && !lp.answers[q.id].firstCorrect).map(q=>q.skill))]};
}
