'use client';

import {useState,useSyncExternalStore,type ReactNode} from 'react';
import {AnimatePresence,useIsPresent,m as motion} from 'framer-motion';
import {ArrowDown,ArrowRight,Check,CheckCircle2,ChevronRight,FlaskConical,Lightbulb,LockKeyhole,ShieldCheck,Trophy,Zap} from 'lucide-react';
import {MISSIONS,advanceMission,replayMission,emptyMission,emptyMissions,earnedMissionXp,mastery,parseMissions,type MissionProgress,type MissionState,type MissionId} from '@/lib/missions';
import type {LearningProgress} from '@/lib/learning';

const KEY='tradeops.missions.v1';
const server={progress:emptyMissions(),saved:true,ready:false};let snapshot=server;const listeners=new Set<()=>void>();
function notify(){listeners.forEach(l=>l());}
function initialize(){if(snapshot.ready)return;try{snapshot={progress:parseMissions(localStorage.getItem(KEY)),saved:true,ready:true};}catch{snapshot={...server,ready:true,saved:false};}}
function sync(e:StorageEvent){if(e.key===KEY){snapshot={progress:parseMissions(e.newValue),saved:true,ready:true};notify();}}
function subscribe(l:()=>void){listeners.add(l);initialize();if(listeners.size===1)window.addEventListener('storage',sync);return()=>{listeners.delete(l);if(!listeners.size)window.removeEventListener('storage',sync);};}
const getSnapshot=()=>snapshot;const getServerSnapshot=()=>server;
export function useMissionProgress(){return useSyncExternalStore(subscribe,getSnapshot,getServerSnapshot);}
function update(fn:(p:MissionProgress)=>MissionProgress){initialize();const progress=fn(snapshot.progress);let saved=true;try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{saved=false;}snapshot={progress,saved,ready:true};notify();}
export function trainingXp(learning:LearningProgress,missions:MissionProgress){return Object.values(learning.lessons).filter(l=>l.completed).length*150+earnedMissionXp(missions);}
export function MasteryBar({learning}:{learning:LearningProgress}) {
  const {progress,saved}=useMissionProgress();const xp=trainingXp(learning,progress);const rank=mastery(xp);
  const wins=MISSIONS.filter(m=>progress.earned.includes(m.id));
  return <section className="mastery-strip" aria-label="Training mastery"><div className="mastery-rank"><span className="rank-emblem"><ShieldCheck size={24}/></span><div><small>YOUR DESK RANK · LEVEL {rank.level}</small><strong>{rank.title}</strong></div></div><div className="mastery-xp"><span><Zap size={14}/>{xp.toLocaleString()} XP <small>{rank.next?`/ ${rank.next.toLocaleString()} next level`:'· top training level'}</small></span><div role="progressbar" aria-label="Skill level progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={rank.next?Math.round((xp-rank.min)/(rank.next-rank.min)*100):100}><motion.i animate={{width:`${rank.next?(xp-rank.min)/(rank.next-rank.min)*100:100}%`}}/></div></div><div className="mastery-achievements"><Trophy size={19}/><span>{wins.length} / 3 mission achievements</span><small>{saved?'Progress saved on this device':'Saving unavailable in this browser'}</small></div></section>;
}
function MissionScreen({children}:{children:ReactNode}){const present=useIsPresent();return <motion.div className="mission-screen" aria-hidden={!present} style={{pointerEvents:present?'auto':'none'}} initial={{opacity:0,y:9}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-7}} transition={{duration:.18}}>{children}</motion.div>;}
const stages=['Order','Execute','Match','Settle','Reconcile'];
const currency=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD'});
export function MissionDesk({onLearn,onExplain}:{onLearn:()=>void;onExplain:(id:string)=>void}) {
  const {progress,saved,ready}=useMissionProgress();const mission=MISSIONS.find(m=>m.id===progress.active)!;const state=progress.cases[mission.id]??emptyMission();
  const [feedback,setFeedback]=useState<{correct:boolean;text:string}|null>(null);const [hint,setHint]=useState(false);
  const value=Math.round(mission.quantity*mission.price*100)/100;const gap=Math.max(0,Math.round((value-mission.cash)*100)/100);
  const setCase=(fn:(s:MissionState)=>MissionState)=>update(p=>({...p,cases:{...p.cases,[mission.id]:fn(p.cases[mission.id]??emptyMission())}}));
  const next=()=>{update(p=>advanceMission(p,mission.id));setFeedback(null);setHint(false);};
  const choose=(id:MissionId)=>{update(p=>({...p,active:id}));setFeedback(null);setHint(false);};
  const replay=()=>{update(p=>replayMission(p,mission.id));setFeedback(null);setHint(false);};
  // The earned ledger survives replay and prevents duplicate XP.
  const checkMatch=()=>{const correct=Number(state.input.replaceAll(',',''))===mission.quantity;setFeedback({correct,text:correct?'Execution evidence verified. Both sides can match the actual traded quantity.':'Use the original execution ticket as evidence. A confirmation can contain a mistake; do not change the trade to make it agree.'});};
  const fund=()=>{setCase(s=>({...s,funded:true}));setFeedback({correct:true,text:`Treasury verified ${currency(gap)} of additional cash in this simulation. The release check is now available.`});};
  const checkRecon=(correct:boolean)=>{setFeedback({correct,text:correct?mission.pending?'The custodian receipt plus the verified pending movement explains the full position. Record the timing item for follow-up.':'The custodian receipt agrees with the executed quantity. Keep the evidence in the audit trail.':'Do not overwrite a record to force a balance. Compare the custodian receipt with verified pending movements first.'});};
  return <section className="mission-world" aria-label="Interactive trade mission">
    <div className="mission-editorial"><span className="eyebrow"><span className="live-dot"/>THE OPERATIONS PLAYGROUND</span><h2>Your next move.<br/><em>Make it count.</em></h2><p>Work the trade. Find the break. Own the outcome. A simulated desk where every decision teaches you something.</p><button className="button primary" onClick={()=>document.getElementById('mission-console')?.focus()}><Zap size={16}/>Enter the simulation<ArrowRight size={16}/></button><button className="editorial-link" onClick={onLearn}>New to operations? Start here<ChevronRight size={15}/></button><div className="mission-proof"><span>03 playable missions</span><i/><span>Zero real trades</span></div></div>
    <div className="mission-stage"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="stage-coordinate">SIM / 001 · EQUITIES</span><div className="mission-selector" role="group" aria-label="Choose a mission">{MISSIONS.map((m,i)=><button key={m.id} aria-pressed={mission.id===m.id} onClick={()=>choose(m.id)}>{progress.earned.includes(m.id)?<Check size={13}/>:<span>0{i+1}</span>}{m.title}</button>)}</div>
      <div className="trade-journey" aria-label="Trade journey timeline">{stages.map((label,i)=><button key={label} className={state.step>i?'done':state.step===i?'current':''} onClick={()=>onExplain(i===2?'matching':i===3?'settlement':i===4?'reconciliation':'trade')} aria-label={`Explain ${label}`}><span>{state.step>i?<Check size={14}/>:i+1}</span><small>{label}</small>{i<4&&<i/>}</button>)}</div>
      <div className="mission-console" id="mission-console" tabIndex={-1}><div className="console-heading"><span><FlaskConical size={13}/>{mission.tag}</span><span className="mission-reward"><Zap size={12}/>300 XP · first completion</span></div>
        <AnimatePresence mode="wait" initial={false}><MissionScreen key={`${mission.id}-${state.step}`}>
          <div className="execution-ticket"><div><small>BUY ORDER / SAMPLE</small><strong>{mission.symbol}<span>USD</span></strong></div><div><small>{mission.quantity} SHARES × {currency(mission.price)}</small><strong>{currency(value)}</strong></div></div>
          {state.step===0&&<><h3>A trade is an agreement.<br/>You make it a good handoff.</h3><p>{mission.description} The sample client has approved the quantity and price shown above.</p><button disabled={!ready} className="button primary" onClick={next}>Accept the sample order<ArrowRight size={16}/></button></>}
          {state.step===1&&<><h3>Execute the training trade.</h3><p>Capture the agreed {mission.quantity} shares at {currency(mission.price)}. Execution records the agreement; it does not mean cash and securities have settled.</p><button className="button primary" onClick={next}>Execute simulated trade<ArrowRight size={16}/></button></>}
          {state.step===2&&<><h3>{mission.confirmation!==mission.quantity?'A confirmation does not line up.':'Verify before you match.'}</h3><p>The counterparty confirmation shows <strong>{mission.confirmation} shares</strong>. Check it against the original execution ticket above.</p><label className="mission-input">Verified execution quantity<input inputMode="numeric" value={state.input} onChange={e=>{setCase(s=>({...s,input:e.target.value}));setFeedback(null);}} placeholder="Number of shares"/></label><div className="mission-actions"><button className="button" onClick={checkMatch} disabled={!state.input.trim()}>Verify quantity</button><button className="button primary" disabled={!feedback?.correct} onClick={next}>Match trade<ArrowRight size={15}/></button></div></>}
          {state.step===3&&<><h3>{gap&&!state.funded?'Hold. There is a funding gap.':'Ready is not settled.'}</h3><div className="settlement-exchange"><span><small>CASH AVAILABLE</small><strong>{currency(mission.cash+(state.funded?gap:0))}</strong></span><ArrowDown size={20}/><span><small>SECURITIES TO RECEIVE</small><strong>{mission.quantity} shares</strong></span></div><p>{gap&&!state.funded?`${currency(value)} is required. Keep the trade on hold and ask Treasury to verify ${currency(gap)} of funding.`:'Cash is verified and the sample securities delivery is ready. Exchange both legs in the simulated delivery-versus-payment settlement.'}</p>{gap&&!state.funded?<button className="button primary" onClick={fund}><LockKeyhole size={15}/>Request verified funding</button>:<button className="button primary" onClick={next}>Settle cash & securities<ArrowRight size={16}/></button>}</>}
          {state.step===4&&<><h3>Close the loop.<br/>Reconcile the evidence.</h3><div className="recon-evidence"><span>Executed <strong>{mission.quantity}</strong></span><span>Custodian received <strong>{mission.custody}</strong></span><span>Verified pending receipt <strong>{mission.pending}</strong></span></div><p>Compare the receipt and any documented pending movement with the executed trade.</p><div className="mission-choices"><button onClick={()=>checkRecon(false)}>Overwrite the custodian record</button><button onClick={()=>checkRecon(true)}>{mission.pending?'Document the verified timing difference':'Confirm records agree and retain evidence'}</button></div><button className="button primary" disabled={!feedback?.correct} onClick={next}>Complete reconciliation<CheckCircle2 size={16}/></button></>}
          {state.step===5&&<div className="mission-complete"><span className="complete-seal"><Trophy size={32}/></span><h3>From trade to trust.</h3><p>You executed, matched, settled and reconciled the sample trade. Achievement unlocked. Your first completion earns 300 XP.</p><div className="mission-actions"><button className="button primary" onClick={()=>choose(MISSIONS[(MISSIONS.findIndex(m=>m.id===mission.id)+1)%MISSIONS.length].id)}>Choose the next mission<ArrowRight size={16}/></button><button className="button" onClick={replay}>Replay mission</button></div></div>}
          {feedback&&<p className={`mission-feedback ${feedback.correct?'correct':'incorrect'}`} role="status">{feedback.text}</p>}
          {state.step<5&&<><button className="mission-hint" onClick={()=>setHint(!hint)} aria-expanded={hint}><Lightbulb size={13}/>{hint?'Hide hint':'Need a hint?'}</button>{hint&&<p className="mission-hint-copy">{state.step===2?'The original execution is the source of truth for quantity.':state.step===3?'The cash shortfall is trade value minus available cash. Verify funding before release.':state.step===4?'Received shares plus a verified pending movement should explain the executed quantity.':'Move through each checkpoint. Matching confirms details; settlement transfers cash and securities.'}</p>}</>}
        </MissionScreen></AnimatePresence>
        <div className="console-footer"><span><span className="live-dot"/>SIMULATION ONLY</span><span>{saved?'CHECKPOINT SAVED':'SAVING UNAVAILABLE'}</span></div>
      </div>
    </div>
  </section>;
}
